openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8011
  description: Generated server url
paths:
  /currencies/convert:
    post:
      tags:
      - currency-controller
      summary: Конвертировать валюту
      description: Конвертирует указанную сумму из одной валюты в другую на основе
        актуального курса.
      operationId: convertCurrency
      requestBody:
        description: "Запрос на конвертацию валюты с указанием исходной валюты, це\
          левой валюты и суммы."
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertCurrencyRequest'
            example:
              fromCurrency: USD
              toCurrency: EUR
              amount: 100.0
        required: true
      responses:
        "400":
          description: Одна из указанных не существует или невалидное тело запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "400"
                code: BadRequest
                message: "Поле amount: must be greater than or equal to 0"
        "200":
          description: Конвертация успешно выполнена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConvertCurrencyResponse'
              example:
                fromCurrency: USD
                toCurrency: RUB
                convertedAmount: "94.4"
        "404":
          description: Валюта с указанным кодом не найдена в ЦБ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "404"
                code: BadRequest
                message: Unsupported currency code - THB
  /currencies/rates/{charCode}:
    get:
      tags:
      - currency-controller
      summary: Получить курс валюты по коду
      description: "Возвращает текущий курс валюты по указанному буквенному коду (н\
        апример, USD, EUR)."
      operationId: getCurrencyRate
      parameters:
      - name: charCode
        in: path
        description: "Буквенный код валюты (например, USD, EUR)"
        required: true
        schema:
          type: string
        example: USD
      responses:
        "400":
          description: Несуществующий формат кода валюты
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "400"
                code: BadRequest
                message: Non-existent currency code - NONNN
        "200":
          description: Курс успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyRateResponse'
              example:
                currency: USD
                rate: "94.15"
                name: Доллар США
        "404":
          description: Валюта с указанным кодом не найдена в ЦБ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "404"
                code: BadRequest
                message: Unsupported currency code - THB
components:
  schemas:
    ConvertCurrencyRequest:
      required:
      - amount
      - fromCurrency
      - toCurrency
      type: object
      properties:
        fromCurrency:
          type: string
        toCurrency:
          type: string
        amount:
          minimum: 0
          type: number
          format: double
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
        code:
          type: string
        message:
          type: string
    ConvertCurrencyResponse:
      required:
      - fromCurrency
      - toCurrency
      type: object
      properties:
        fromCurrency:
          type: string
        toCurrency:
          type: string
        convertedAmount:
          type: string
    CurrencyRateResponse:
      type: object
      properties:
        currency:
          type: string
        rate:
          type: string
        name:
          type: string
